DROP TABLE Logs;
DROP TABLE Statistic;
CREATE TABLE Logs(str STRING);
CREATE TABLE Statistic(ip STRING,avg DOUBLE,sum INT);
LOAD DATA LOCAL INPATH 'input.txt' OVERWRITE INTO TABLE Logs;
INSERT INTO Statistic SELECT t.ip,AVG(CASE WHEN num IS NOT NULL THEN num ELSE 0 END), SUM(CASE WHEN num IS NOT NULL THEN num ELSE 0 END) FROM (SELECT REGEXP_EXTRACT(str,'ip\\d+ ',0) AS ip,CAST(SPLIT(REGEXP_EXTRACT(str,' \\d+ \\d+ ',0),' ')[2] AS DOUBLE) AS num FROM Logs) t GROUP BY t.ip;
SELECT * FROM Statistic;